server:
  port: 8091

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/demo-shiro
    username: root
    password: Magustek
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
